In [3]:
# Labelencoding
# 컬럼 값들의 종류가 많을 때
# 회귀에는 쓰이기 힘들다
# 분류 모델 경우 사용가능

from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서기','믹서기']

encoder = LabelEncoder()

labels = encoder.fit_transform(items)
print('인코딩 변환값 :',labels)

인코딩 변환값 : [0 1 4 5 3 3 2 2]


In [4]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서기' '선풍기' '전자레인지' '컴퓨터']


In [7]:
print('디코딩 원본 값 :',encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

디코딩 원본 값 : ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서기' '믹서기']


In [15]:
# Onehotencoding
# 
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서기','믹서기']

encoder = LabelEncoder()

labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1)
labels

oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print('OneHotEncoding :')
print(oh_labels.toarray())

OneHotEncoding :
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [23]:
# 과제
import pandas as pd
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서기','믹서기']

# pd.get_dummies()를 사용하여 원핫인코딩 하세요.
df = pd.DataFrame(items,columns=['전자제품'])
pd.get_dummies(df)

전자제품_TV  전자제품_냉장고  전자제품_믹서기  전자제품_선풍기  전자제품_전자레인지  전자제품_컴퓨터
0        1         0         0         0           0         0
1        0         1         0         0           0         0
2        0         0         0         0           1         0
3        0         0         0         0           0         1
4        0         0         0         1           0         0
5        0         0         0         1           0         0
6        0         0         1         0           0         0
7        0         0         1         0           0         0

In [45]:
# 과제
# 붓꽃 데이터 셋의 독립변수들을 정규화 한 후 평균값과 분산값을 출력하세요.
# - 0과 1 사이의 분포로 스케일링 : MINMAX
# - 평균 0 표준편차 1인 분포로 스케일링 : STANDARD
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_data = pd.DataFrame(iris_data,columns=iris.feature_names)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

mmscaler = MinMaxScaler()
sscaler = StandardScaler()

ms_iris_data = mmscaler.fit_transform(iris_data)
ms_iris_data = pd.DataFrame(ms_iris_data,columns=iris_data.columns)
ss_iris_data = sscaler.fit_transform(iris_data)
ss_iris_data = pd.DataFrame(ss_iris_data,columns=iris_data.columns)


na = iris_data.mean().round(3)
nb = iris_data.std(ddof=1).round()

a = ms_iris_data.mean().round(3)
b = ms_iris_data.std(ddof=1).round(3)

c = ss_iris_data.mean().round(3)
d = ss_iris_data.std(ddof=1).round(3)

print('기존 평균값 : {}, 분산값 : {}'.format(na,nb))
print('MinMax 평균값 : {}, 분산값 : {}'.format(a,b))
print('Standard 평균값 : {}, 분산값 : {}'.format(c,d))


기존 평균값 : sepal length (cm)    5.843
sepal width (cm)     3.057
petal length (cm)    3.758
petal width (cm)     1.199
dtype: float64, 분산값 : sepal length (cm)    1.0
sepal width (cm)     0.0
petal length (cm)    2.0
petal width (cm)     1.0
dtype: float64
MinMax 평균값 : sepal length (cm)    0.429
sepal width (cm)     0.441
petal length (cm)    0.467
petal width (cm)     0.458
dtype: float64, 분산값 : sepal length (cm)    0.230
sepal width (cm)     0.182
petal length (cm)    0.299
petal width (cm)     0.318
dtype: float64
Standard 평균값 : sepal length (cm)   -0.0
sepal width (cm)    -0.0
petal length (cm)   -0.0
petal width (cm)    -0.0
dtype: float64, 분산값 : sepal length (cm)    1.003
sepal width (cm)     1.003
petal length (cm)    1.003
petal width (cm)     1.003
dtype: float64
