[모집단 분포와 표본분포]
- 모집단: 어떤 통계적 실험의 대상이 되는 모든 대상물. ex. 대한민국 모든 남성의 키 데이터, 2018 수능점수 데이터

- 모집단 분포: 모집단은 데이터 집단이므로 어떠한 분포를 이루며 이 데이터가 이루는 확률 분포가 모집단 분포

- 모수: 모집단의 특성을 나타내는 수치로 모평균, 모분산, 모표준편차, 모비율, 모상관관계 등 수능점수 전체데이터를 알고 싶은 것이 아니라 전체 수능점수 평균, 표준편차를 알고 싶어한다.  수능점수와 달리 일반적으로 대부분의 모집단 분포는 완전하게 알려진 것이 없으며 전수조사는 경제적, 공간적, 시간적 제약으로 인해 거의 불가능
- 표본: 모집단의 모수(특성)을 알기 위하여 표본을 추출해서 모집단의 모수를 추정
- 확률표본: 모집단을 구성하는 모든 구성원이 표본으로 뽑힐 확률을 동일하게 하여 추출한 표본. Random이란 무작위라는 의미로, 어떠한 의도를 가지지 않는다는 것을 의미하며, 모든 구 성원이 뽑힐 확률이 동일하다는 개념
- 통계량: 확률표본의 특성을 설명하는 값으로 표본평균, 표본분산, 표본표준편차, 표본비율, 표본상관관계 등\
모수는 모집단이 변하지 않기 때문에 그 값이 변하지 않으나 통계량은 표본을 어떻게 추출하 느냐에 따라서 그 값이 다르게 나타난다.
- 확률변수: 무작위 실험을 했을 때 특정 확률로 발생하는 각각의 결과를 수치값으로 표현한 변
수, 동전의 앞과 뒤
- 확률분포: 확률변수 X의 모든 값과 그 에 대응하는 확률값들의 분포, 동전의 앞 0.5, 뒤 0.5\
무작위로 표본 30개씩 반복해서 100번 추출하면 100번 추출한 표본 30개의 평균값들을 100 개 구할 수 있다. 추출된 표본들의 각 평균값들에 대한 발생 분포를 그려보면 특정 확률변수에 대응하는 확률을 가진 확률 분포를 그릴 수 있다. 이것을 통계량의 확률분포라고 할 수 있고 이를 표본분포라고 부른다.
- 통계량이 확률 변수라는 의미: 확률변수의 확률분포가 수학적으로 설명가능한 분포(예, 정규
분포)를 따른다고 하면 특정 확률변수와 확률함수를 알고 있다면 특정 사건이 일어날 확률을 계산할 수 있으며 더 나아가 모수와 통계량의 관계를 알고 있다면 그것을 통해 모수에 대한 통 계적인 추정을 할 수 있다. 즉 통계량의 확률 함수 또는 표본 분포를 안다고 가정하면 이를 이 용해 모수를 추정할 수 있다.


In [3]:
import numpy as np
import pandas as pd
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data


array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [5]:
np.sum(fish_data)

40

In [6]:
len(fish_data)

10

In [10]:
# 평균
N = len(fish_data)
sum_value = np.sum(fish_data)
mu = sum_value / N
mu

4.0

In [11]:
np.mean(fish_data)

4.0

In [12]:
# 표본분산
sigma_2_sample = np.sum((fish_data-mu)**2)/N
sigma_2_sample

1.2

In [16]:
np.var(fish_data)
#np.var(fish_data,ddof=1)

1.2

In [17]:
# 표본편차
np.std(fish_data)

1.0954451150103321

In [18]:
np.var(fish_data,ddof=0)

1.2

In [20]:
np.std(fish_data,ddof=0)

1.0954451150103321

In [21]:
# 불편분산
np.var(fish_data,ddof=1)

1.3333333333333333

In [23]:
# 불편표준편차
np.std(fish_data,ddof=1).round(2)
std2 = np.std(fish_data,ddof=1)
np.round(std2,2)

1.15

In [34]:
# a의 평균, 분산, 표준편차, 편차의 평균을 구하세요
a = np.arange(15)
print(np.mean(a)) # 평균
print(np.var(a,ddof=1)) # 분산
print(np.std(a,ddof=1)) # 표준편차
print(np.mean(a - np.mean(a))) # 편차의 평균
print(a-np.mean(a)) # 편차

7.0
20.0
4.47213595499958
0.0
[-7. -6. -5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.  6.  7.]


In [50]:
from scipy import stats
stats.scoreatpercentile(fish_data,[25,75]) # 1,3사분위


array([3.25, 4.75])

In [45]:
fish_data2 = np.array([2,3,3,4,4,4,4,5,5,6,100])

In [48]:
print(fish_data2)
print('평균 : ',fish_data2.mean().round(2))
print('중앙 값 : ',np.median(fish_data2))

[  2   3   3   4   4   4   4   5   5   6 100]
평균 :  12.73
중앙 값 :  4.0


In [53]:
import pandas as pd
fish_multi = pd.read_csv('dataset/5_2_fm.csv')
fish_multi

species  length
0       A       2
1       A       3
2       A       4
3       B       6
4       B       8
5       B      10

In [57]:
# 그룹별 통계량 계산
grouped = fish_multi.groupby('species')
print(grouped.mean())
print(grouped.std())
print(grouped.describe())

# 한 줄 요약
# display(fish_multi.groupby('species').agg(['mean','var','std']))

         length
species        
A           3.0
B           8.0
         length
species        
A           1.0
B           2.0
        length                                    
         count mean  std  min  25%  50%  75%   max
species                                           
A          3.0  3.0  1.0  2.0  2.5  3.0  3.5   4.0
B          3.0  8.0  2.0  6.0  7.0  8.0  9.0  10.0


In [58]:
cov_data = pd.read_csv('dataset/4_cov.csv')
cov_data

x   y
0  18.5  34
1  18.7  39
2  19.1  41
3  19.7  38
4  21.5  45
5  21.7  41
6  21.8  52
7  22.0  44
8  23.4  44
9  23.8  49

In [66]:
# 과제 1
# 공분산을 풀어서 구하세요
x_r = np.mean(cov_data.x)
y_r = np.mean(cov_data.y)

np.sum((cov_data.x - x_r) * (cov_data.y - y_r)) / (len(cov_data)-1)


7.673333333333336

In [69]:
# 과제 2
# 상관계수를 풀어서 구하세요
cov = np.cov(cov_data.x,cov_data.y) # 공분산
x1 = np.std(cov_data.x,ddof=1) # x의 표본표준편차
y1 = np.std(cov_data.y,ddof=1) # y의 표본표준편차
result = cov / (x1 * y1)
result

array([[0.36079158, 0.7592719 ],
       [0.7592719 , 2.77168328]])

In [65]:
# 공분산 행렬 (함수)
np.cov(cov_data.x,cov_data.y,ddof=1)

array([[ 3.64622222,  7.67333333],
       [ 7.67333333, 28.01111111]])

In [67]:
# 상관 행렬
np.corrcoef(cov_data.x,cov_data.y)

array([[1.       , 0.7592719],
       [0.7592719, 1.       ]])