## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : Python 분석라이브러리 활용

- 평가일 : 21.7. 23
- 성명 : 신인철
- 점수 :

### Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
[0 1 2 3 4 5 6 7 8 9]  

[[0 1 2 3 4]  
 [5 6 7 8 9]]  
 
[[[0 1 2 3 4]  
  [5 6 7 8 9]]]

In [11]:
import numpy as np
a = np.arange(10)
print(a,'\n')
b = a.reshape(2,5)
print(b,'\n')
c = a.reshape((1,2,5))
print(c,'\n')


[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 



### Q2. 1 ~ 100 까지 배열에서 3과 7의 공배수인 것만을 출력하세요.

In [168]:
ar = np.arange(1,101)
ar[np.where((ar % 3 == 0) & (ar % 7 == 0))]

array([21, 42, 63, 84])

### Q3. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3  4]  
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]  
   [15 16 17 18 19]]

 [[20 21 22 23 24]  
   [25 26 27 28 29]]]

In [24]:
a = np.arange(30).reshape(3,2,5)
print(a,'\n')
b = a.reshape(-1)
print(b)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


### Q4. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(1,10).reshape(3,3)

[3, 6]  

[[1, 2],  
[4, 5]]

[[1, 2, 3]  
[4, 5, 6]]

In [30]:
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d[:2,-1],'\n')
print(arr2d[:2,:2],'\n')
print(arr2d[:2],'\n')

[3 6] 

[[1 2]
 [4 5]] 

[[1 2 3]
 [4 5 6]] 



### Q5. 아래 두행렬을 np.arange, reshape를 이용해서 생성 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하세요.

[[1 2 3]  
 [4 5 6]  
 [7 8 9]]

[[10 11 12]  
 [13 14 15]  
 [16 17 18]]

In [34]:
a1 = np.arange(1,10).reshape(3,3)
b1 = np.arange(10,19).reshape(3,3)
x=a1
y=b1
np.dot(x,y)


array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

### Q6. ar의 역행렬을 출력하고 검증을 수행하세요.

In [38]:
np.random.seed(1)
ar = np.random.randint(1,4,size=(3,3))
ar2 = np.linalg.inv(ar)
np.dot(ar,ar2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Q7. 10 ~ 20 사이의 정수 난수로 10행 5열 2차원 배열을 생성하고 저장한 후 다시 불러내서 출력하세요.

In [46]:
a = np.random.randint(10,21,size=(10,5))
np.save('array_wow',a)

np.load('array_wow.npy')

array([[10, 12, 10, 20, 17],
       [11, 17, 19, 18, 20],
       [14, 10, 11, 19, 18],
       [12, 13, 11, 12, 17],
       [12, 20, 16, 10, 19],
       [12, 16, 16, 12, 17],
       [17, 10, 16, 15, 11],
       [20, 14, 16, 10, 16],
       [15, 11, 12, 11, 15],
       [14, 20, 10, 17, 18]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived'외에 모든 칼럼을 포함한 df_x를 산출한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [51]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset('titanic')

df_x = df.drop('survived',axis=1)
df_x.to_pickle('dataset/df_x.pkl')

df_x = pd.read_pickle('dataset/df_x.pkl')
df_x

pclass     sex   age  sibsp  ...  deck  embark_town alive  alone
0         3    male  22.0      1  ...   NaN  Southampton    no  False
1         1  female  38.0      1  ...     C    Cherbourg   yes  False
2         3  female  26.0      0  ...   NaN  Southampton   yes   True
3         1  female  35.0      1  ...     C  Southampton   yes  False
4         3    male  35.0      0  ...   NaN  Southampton    no   True
..      ...     ...   ...    ...  ...   ...          ...   ...    ...
886       2    male  27.0      0  ...   NaN  Southampton    no   True
887       1  female  19.0      0  ...     B  Southampton   yes   True
888       3  female   NaN      1  ...   NaN  Southampton    no  False
889       1    male  26.0      0  ...     C    Cherbourg   yes   True
890       3    male  32.0      0  ...   NaN   Queenstown    no   True

[891 rows x 14 columns]

### Q9. df = sns.load_dataset('titanic')로 불러와서 deck 열에서 NaN 갯수를 계산하세요.

In [40]:
# A.
# deck 열의 NaN 개수 계산하기
import seaborn as sns
df = sns.load_dataset('titanic')
print(df['deck'].isnull().sum(axis=0))

688


### Q10. Q9의 df에서 각 칼럼별 null 개수와 df 전체의 null 개수를 구하세요.

In [54]:
print(df.isnull().sum().sum())
df.isnull().sum()

869


survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### 아래 tdf 데이터프레임에서 Q11 ~ Q12 작업을 수행하세요.

In [55]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

### Q11. age를 7개 카테고리로 구분하는 새로운 칼럼 'cat_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 age 칼럼에 매핑하여 결과를 tdf1에 저장하고 출력하세요.

[카테고리]  
age <= 5: cat = 'Baby'  
age <= 12: cat = 'Child'  
age <= 18: cat = 'Teenager'  
age <= 25: cat = 'Student'  
age <= 60: cat = 'Adult'  
age > 60 : cat = 'Elderly'

In [170]:
 
def age__tran(a):
    if a <=  5:
        cat = 'Baby'
    elif a <= 12:
        cat = 'Child'
    elif a <= 18:
        cat = 'Teenager'
    elif a <= 25:
        cat = 'Student'
    elif a <= 60:
        cat = 'Adult'
    elif a > 60:
        cat = 'Elderly'
    return cat
tdf['age_cat'] = map(lambda x : age__tran(x),tdf.age)
tdf


TypeError: object of type 'map' has no len()

### Q12.  tdf1의 sex, class 칼럼을 '_'으로 연결한 'sc'칼럼을 추가한 후 아래와 같이 출력하세요.



In [71]:
tdf1

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- df1과 df2의 교집합만 출력되도록 결합하여 df4에 저장하고 출력
- df4에서 중복된 칼럼을 삭제한 후 블린 인덱싱을 이용하여 eps가 3000 보다 적거나 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df5 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [99]:
df1 = pd.read_excel('stock price.xlsx')
df2 = pd.read_excel('stock valuation.xlsx')
df4 = df1.join(df2,lsuffix='_1',rsuffix='_2',how='inner')
print(df4.info())
def wow(a,b):
    if a < 3000 | b =='이마트':
        return a, b
    else:
        pass

df4.apply(wow(df4['eps'],df4['stock_name']))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id_1        10 non-null     int64  
 1   stock_name  10 non-null     object 
 2   value       10 non-null     float64
 3   price       10 non-null     int64  
 4   id_2        10 non-null     int64  
 5   name        10 non-null     object 
 6   eps         10 non-null     float64
 7   bps         10 non-null     int64  
 8   per         10 non-null     float64
 9   pbr         10 non-null     float64
dtypes: float64(4), int64(4), object(2)
memory usage: 928.0+ bytes
None


TypeError: Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]

### Q14. 아래 df에서 drop_duplicates() 메소드를 사용하여 c4, c5열을 기준으로 중복 행을 제거한 후 df3에 저장하고 출력하세요.

In [1]:
import pandas as pd
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2],
                  'c4':[1, 1, 1, 2, 3],
                  'c5':[1, 1, 2, 2, 5]})
print(df)

  c1  c2  c3  c4  c5
0  a   1   1   1   1
1  a   1   1   1   1
2  b   1   2   1   2
3  a   2   2   2   2
4  b   2   2   3   5


### Q15. 'mpg'를 'kpl' 로 환산하여 새로운 열을 생성하고 처음 3개 행을 소수점 아래 둘째 자리에서 반올림하여 출력하세요.

In [92]:
import pandas as pd
auto_df = pd.read_csv('dataset/auto-mpg.csv')

auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
print(auto_df.head(3))

def mtk(a):
    mpg_to_kpl = (a * 1.60934) / 3.78541
    return mpg_to_kpl

round(auto_df['mpg'].apply(mtk),2)

    mpg  cylinders  displacement  ... model year  origin                       name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite

[3 rows x 9 columns]


0       7.65
1       6.38
2       7.65
3       6.80
4       7.23
       ...  
393    11.48
394    18.71
395    13.60
396    11.90
397    13.18
Name: mpg, Length: 398, dtype: float64

### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 datetime64 자료형으로 변환한 후에 년, 월, 일로 분리하고 year를 인덱스로 셋팅하여 출력하세요.

### Q17. titanic 데이터셋에서 5개 열을 선택해서 class열을 기준으로 그룹화를 수행한 후 아래와 같이 출력하였다. 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

In [157]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.dropna(inplace=True)
df_s = df.groupby(['age','sex', 'class', 'fare', 'survived'])
df_s1 = df_s.get_group('class')
print(df_s1.mean())
df_s1.max()

ValueError: must supply a tuple to get_group with multiple grouping keys

### Q18. titanic 데이터셋에서 'Third'그룹만을 선택해서 group3 이름으로 저장하고 통계요약표를 출력하세요.

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.groupby

### Q19. titanic 데이터셋에서 class 열, sex열 기준으로 그룹화한 후 그룹별 평균과 표준편차를 구하세요.

In [133]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()
df9 = df.groupby(['class','sex'])
print(df9.mean())
print(df9.std())


               survived  pclass        age  ...        fare  adult_male     alone
class  sex                                  ...                                  
First  female  0.968085     1.0  34.611765  ...  106.125798    0.000000  0.361702
       male    0.368852     1.0  41.281386  ...   67.226127    0.975410  0.614754
Second female  0.921053     2.0  28.722973  ...   21.970121    0.000000  0.421053
       male    0.157407     2.0  30.740707  ...   19.741782    0.916667  0.666667
Third  female  0.500000     3.0  21.750000  ...   16.118810    0.000000  0.416667
       male    0.135447     3.0  26.507589  ...   12.661633    0.919308  0.760807

[6 rows x 8 columns]
               survived  pclass        age  ...       fare  adult_male     alone
class  sex                                  ...                                 
First  female  0.176716     0.0  13.612052  ...  74.259988    0.000000  0.483070
       male    0.484484     0.0  15.139570  ...  77.548021    0.155511  0.48866

### Q20.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [129]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

laen = LabelEncoder()

df = sns.load_dataset('titanic')
df1 = df.drop(['class','who','adult_male','alive','alone','embark_town'],axis=1)
df2 = df1.drop('deck',axis=1)
df2['age'] = df2['age'].fillna(df2.age.mean())
df2['embarked'] = df2['embarked'].ffill()

li = ['sex','embarked']
for i in li:
    df2[i] = laen.fit_transform(df2[i])

df2.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    int64  
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB
