## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : Python 분석라이브러리 활용

- 평가일 : 21.7.26
- 성명 : 
- 점수 :

### Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
1차원  
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]  

2차원  
[[ 1  2  3  4  5]  
  [ 6  7  8  9 10]  
  [11 12 13 14 15]  
  [16 17 18 19 20]] 

3차원  
[[[ 1  2  3  4  5]  
  [ 6  7  8  9 10]]  
 
 [[11 12 13 14 15]  
  [16 17 18 19 20]]]

In [3]:
# A.
import numpy as np
ar = np.arange(1,21)
ar1 = ar.reshape(-1,)
ar2 = ar.reshape(-1,5)
ar3 = ar.reshape(2,2,-1)
print('1차원')
print(ar1,'\n')
print('2차원')
print(ar2,'\n')
print('3차원')
print(ar3)

1차원
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

2차원
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

3차원
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


### Q2. 1 ~ 100 까지 배열에서 3과 7의 공배수중에서 42의 배수인 것만을 출력하세요.

In [13]:
# A.
import numpy as np
a1 = np.arange(1,101)
a1 = a1[((a1 % 3 ==0) & (a1 % 7==0)) & (a1 % 42 == 0)]
a1

array([42, 84])

### Q3. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3]  
  [ 4  5  6  7]  
  [ 8  9 10 11]]  
  
 [[12 13 14 15]  
  [16 17 18 19]  
  [20 21 22 23]]]

In [16]:
# A.
arr3d = np.arange(24).reshape(2,3,-1)
print(arr3d)
arr1d = arr3d.reshape(-1,)
arr1d

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Q4. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(11,20).reshape(3,3)

[13 16]  

[[11 12]  
 [14 15]]

[[11 12 13]  
 [14 15 16]]

In [17]:
# A.
arr2d = np.arange(11,20).reshape(3,3)
print(arr2d)
print(arr2d[[0,1],2])
print(arr2d[[0,1],0:2])
print(arr2d[[0,1],:])

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[13 16]
[[11 12]
 [14 15]]
[[11 12 13]
 [14 15 16]]


### Q5. 아래 두행렬을 np.arange, reshape를 이용해서 생성 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하세요.

[[ 1  2  3  4  5]  
 [ 6  7  8  9 10]  
 [11 12 13 14 15]]

[[10 11 12 13  
 [14 15 16 17]  
 [18 19 20 21]  
 [22 23 24 25]  
 [26 27 28 29]]

In [20]:
# A.
import numpy as np
a1 = np.arange(1, 16).reshape(3,5)
b1 = np.arange(10, 30).reshape(5,4)
ab_product = np.dot(a1,b1)
print(a1,'\n')
print(b1,'\n')
print(ab_product)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]] 

[[ 310  325  340  355]
 [ 760  800  840  880]
 [1210 1275 1340 1405]]


### Q6. ar의 역행렬을 출력하고 검증을 수행하세요.(지수표현식을 실수 표현으로 변경)
np.set_printoptions(precision=6, suppress=True)

In [21]:
np.random.seed(1)
ar = np.random.randint(1,6,size=(5,5))
ar

array([[4, 5, 1, 2, 4],
       [1, 1, 2, 5, 5],
       [2, 3, 5, 3, 5],
       [4, 5, 3, 5, 3],
       [5, 2, 2, 1, 2]])

In [29]:
# A.
np.set_printoptions(precision=6, suppress=True) # 지수표현식(과학적표기법)을 실수 표현으로
rar = np.linalg.inv(ar)
print(rar,'\n')
print(np.dot(ar,rar))

[[-0.039801  0.039801 -0.11194  -0.012438  0.278607]
 [ 0.174129 -0.174129  0.052239  0.116915 -0.218905]
 [-0.195688 -0.137645  0.241294  0.063847  0.036484]
 [-0.139303  0.139303 -0.141791  0.206468 -0.024876]
 [ 0.190713  0.14262   0.057214 -0.252902 -0.001658]] 

[[ 1. -0.  0.  0. -0.]
 [-0.  1. -0. -0. -0.]
 [-0.  0.  1.  0. -0.]
 [ 0.  0.  0.  1. -0.]
 [ 0.  0.  0.  0.  1.]]


### Q7. 표준정규분포 난수로 10행 5열 2차원 배열 ar을 생성하고 ar_test 이름으로 저장한 후 다시 불러내서 출력하세요.

In [30]:
# A.
import numpy as np
import pandas as pd
np.random.seed(0)
ar = np.random.randn(10,5)
np.save('ar_test',ar)
np.load('ar_test.npy')

array([[ 1.764052,  0.400157,  0.978738,  2.240893,  1.867558],
       [-0.977278,  0.950088, -0.151357, -0.103219,  0.410599],
       [ 0.144044,  1.454274,  0.761038,  0.121675,  0.443863],
       [ 0.333674,  1.494079, -0.205158,  0.313068, -0.854096],
       [-2.55299 ,  0.653619,  0.864436, -0.742165,  2.269755],
       [-1.454366,  0.045759, -0.187184,  1.532779,  1.469359],
       [ 0.154947,  0.378163, -0.887786, -1.980796, -0.347912],
       [ 0.156349,  1.230291,  1.20238 , -0.387327, -0.302303],
       [-1.048553, -1.420018, -1.70627 ,  1.950775, -0.509652],
       [-0.438074, -1.252795,  0.77749 , -1.613898, -0.21274 ]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived','who','adult_male','deck','embark_town','alive','alone' 칼럼을 제외한
df_x 데이터프레임을 생성한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [31]:
# A.
import seaborn as sns
import pandas as pd

# titanic 데이터셋 가져오기
df = sns.load_dataset('titanic')
df_x = df.drop(['survived','who','adult_male','deck','embark_town','alive','alone'],axis=1)
df_x.to_pickle('dataset/df_x.pkl')
df_x = pd.read_pickle('dataset/df_x.pkl')
df_x.head()

pclass     sex   age  sibsp  parch     fare embarked  class
0       3    male  22.0      1      0   7.2500        S  Third
1       1  female  38.0      1      0  71.2833        C  First
2       3  female  26.0      0      0   7.9250        S  Third
3       1  female  35.0      1      0  53.1000        S  First
4       3    male  35.0      0      0   8.0500        S  Third

### Q9. Q.8의 df_x에서 각 칼럼별 null 개수를 구하세요.

In [35]:
# A.
df_x.isnull().sum()

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
class         0
dtype: int64

### Q10. df_x의 전체 null 갯수를 계산하세요.

In [34]:
# A.
df_x.isnull().sum().sum()

179

### Q11. tdf에서 fare를 3개 카테고리로 구분하는 새로운 칼럼 'fare_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 fare 칼럼에 매핑하여 결과를 tdf에 저장하고 출력하세요.

[카테고리]  
fare <= 7.9: cat = 'T'  
fare <= 31: cat = 'S'  
fare > 31 : cat = 'F'

In [39]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class','fare']]
tdf.head()

survived     sex   age  class     fare
0         0    male  22.0  Third   7.2500
1         1  female  38.0  First  71.2833
2         1  female  26.0  Third   7.9250
3         1  female  35.0  First  53.1000
4         0    male  35.0  Third   8.0500

In [50]:
# A.
import warnings
warnings.filterwarnings('ignore')
def fare_cat(x):
    cat = ''
    if x <= 7.9:
        cat = 'T'
    elif x <= 31:
        cat = 'S'
    else:
        cat = 'F'
    return cat
tdf['fare_cat'] = tdf.fare.apply(fare_cat)
tdf.head()

survived     sex   age  class     fare fare_cat
0         0    male  22.0  Third   7.2500        T
1         1  female  38.0  First  71.2833        F
2         1  female  26.0  Third   7.9250        S
3         1  female  35.0  First  53.1000        F
4         0    male  35.0  Third   8.0500        S

### Q12.  df의 gender, code 칼럼을 '_'으로 연결한 'gc'칼럼을 추가한 후 출력하세요. 단, 타입변환을 유의해서 수행하세요.
연결 예시 : m_10

In [73]:
df = pd.DataFrame({'gender' : ['m', 'f', 'f'],\
                   'code' : [10, 20, 30]})
df

gender  code
0      m    10
1      f    20
2      f    30

In [76]:
# A.
df['gc'] = df[['gender','code']].astype(str).apply('_'.join, axis=1)
df

gender  code    gc
0      m    10  m_10
1      f    20  f_20
2      f    30  f_30

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- 데이터 셋
1. 'dataset/stock price.xlsx'
2. 'dataset/stock valuation.xlsx'
- df1과 df2의 합집합이 출력되도록 결합하여 df4에 저장하고 출력
- df4에서 중복된 칼럼 name 을 삭제한 후 블린 인덱싱을 이용하여 eps가 10000 보다 크고 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df5 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [80]:
!pip install openpyxl

  Using cached openpyxl-3.0.7-py2.py3-none-any.whl (243 kB)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)


In [92]:
# A.
pd.set_option('max_columns',10)
# pd.set_option('max_rows',5)
df1 = pd.read_excel('dataset/stock price.xlsx', index_col='id')
df2 = pd.read_excel('dataset/stock valuation.xlsx', index_col='id')
print(df1.head(),'\n')
print(df2.head(),'\n')
df4 = df1.join(df2,how='outer')
print(df4)
print()
df4.drop('name', axis=1, inplace=True)

df5 = df4[(df4['eps'] > 10000) & (df4['stock_name'] == '이마트')]
df5

       stock_name          value   price
id                                      
128940       한미약품   59385.666667  421000
130960     CJ E&M   58540.666667   98900
138250      엔에스쇼핑   14558.666667   13200
139480        이마트  239230.833333  254500
142280     녹십자엠에스     468.833333   10200 

           name           eps     bps        per       pbr
id                                                        
130960   CJ E&M   6301.333333   54068  15.695091  1.829178
136480       하림    274.166667    3551  11.489362  0.887074
138040  메리츠금융지주   2122.333333   14894   6.313806  0.899691
139480      이마트  18268.166667  295780  13.931338  0.860437
145990      삼양사   5741.000000  108090  14.283226  0.758627 

       stock_name         value     price      name          eps      bps  \
id                                                                          
128940       한미약품  59385.666667  421000.0       NaN          NaN      NaN   
130960     CJ E&M  58540.666667   98900.0    CJ E&M  6301.333333 

stock_name          value     price           eps       bps        per  \
id                                                                              
139480        이마트  239230.833333  254500.0  18268.166667  295780.0  13.931338   

             pbr  
id                
139480  0.860437

### Q14.  df의 score1 과 score2 컬럼을 합한 숫자로 구성된 새로운 컬럼 score3을 생성 후 df를 출력하세요.

In [10]:
import numpy as np
import pandas as pd
np.random.seed(0)
df = pd.DataFrame(np.random.randint(123456789,123456791,size=(2,2)),columns= ['score1','score2'])
df['score1'] = '123,234,567'
df

score1     score2
0  123,234,567  123456790
1  123,234,567  123456789

In [18]:
# A.
import re
df['score1'] = df.score1.apply(lambda x : re.sub(',','',x)) 
df['score3'] = df.score1.astype(int) + df.score2
df

score1     score2     score3
0  123234567  123456790  246691357
1  123234567  123456789  246691356

### Q15. auto_df의 horsepower 컬럼에서 숫자가 아닌 원소들을 0으로 대체한 후에 전체 평균을 구한 후 소숫점 2째 자리까지만 출력하세요.

In [43]:
import pandas as pd
auto_df = pd.read_csv('dataset/auto-mpg.csv')
auto_df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [48]:
# A
auto_df.horsepower.replace('?',0,inplace=True)
auto_df['horsepower'] = auto_df.horsepower.astype(float)
auto_df.horsepower.mean().round(2)

102.89

### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 Date 컬럼 판다스 Timestamp로 변환한 후 인덱스로 셋팅하고 Date 컬럼은 삭제한 후 처음 5개 행만 출력하세요.

In [53]:
# A.
# 날짜 데이터 분리

import pandas as pd

# read_csv() 함수로 파일 읽어와서 df로 변환
df = pd.read_csv('dataset/stock-data.csv')

# 문자열인 날짜 데이터를 판다스 Timestamp로 변환
df['new_Date'] = pd.to_datetime(df['Date'])   #df에 새로운 열로 추가
df.drop('Date',axis=1,inplace=True)
df.set_index('new_Date').head()

Close  Start   High    Low  Volume
new_Date                                      
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

### Q17. titanic 데이터셋에서 아래 5개 열을 선택하고 sex 컬럼을 기준으로 그룹화를 수행한 후 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

In [56]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

In [64]:
# A.
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

print(df.head())
print()
# class 열을 기준으로 분할(1개 열을 기준)
grouped = df.groupby(['sex'])
print('그룹별 평균')
average = grouped.mean()
print(average)
print()
print('그룹별 최대값')
stat = grouped.max()
print(stat)

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

그룹별 평균
              age       fare  survived
sex                                   
female  27.915709  44.479818  0.742038
male    30.726645  25.523893  0.188908

그룹별 최대값
         age      fare  survived
sex                             
female  63.0  512.3292         1
male    80.0  512.3292         1


### Q18. titanic 데이터셋에서 class, age, fare, survived 4개 컬럼만 선택하여 df를 생성한 후 class 컬럼의  'First'그룹만을 선택해서 group1 이름으로 저장하고 통계요약표를 출력하세요.

In [65]:
# A.
titanic = sns.load_dataset('titanic')
df = titanic[['class','sex', 'age', 'fare', 'survived']]
print(df.head(),'\n')
grouped = df.groupby(['class'])
group1 = grouped.get_group('First')
group1.describe()

   class     sex   age     fare  survived
0  Third    male  22.0   7.2500         0
1  First  female  38.0  71.2833         1
2  Third  female  26.0   7.9250         1
3  First  female  35.0  53.1000         1
4  Third    male  35.0   8.0500         0 



age        fare    survived
count  186.000000  216.000000  216.000000
mean    38.233441   84.154687    0.629630
std     14.802856   78.380373    0.484026
min      0.920000    0.000000    0.000000
25%     27.000000   30.923950    0.000000
50%     37.000000   60.287500    1.000000
75%     49.000000   93.500000    1.000000
max     80.000000  512.329200    1.000000

### Q19. titanic 데이터셋에서 class 열, sex열 기준으로 그룹화한 후 그룹별 최대값과 최소값을 구하세요.

In [66]:
titanic = sns.load_dataset('titanic')
df = titanic[['class','sex', 'age', 'fare', 'survived']]

In [68]:
# A.
grouped = df.groupby(['class', 'sex']) 
gdf = grouped.max()
print(gdf)
print()
gdf = grouped.min()
print(gdf)

                age      fare  survived
class  sex                             
First  female  63.0  512.3292         1
       male    80.0  512.3292         1
Second female  57.0   65.0000         1
       male    70.0   73.5000         1
Third  female  63.0   69.5500         1
       male    74.0   69.5500         1

                age     fare  survived
class  sex                            
First  female  2.00  25.9292         0
       male    0.92   0.0000         0
Second female  2.00  10.5000         0
       male    0.67   0.0000         0
Third  female  0.75   6.7500         0
       male    0.42   0.0000         0


### Q20.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'deck' 컬럼만을 선택하여 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼은 삭제한 후 df2를 생성하고 df2에 null이 있는 컬럼은 적절한 값으로 대체한 후 df2의 null값의 갯수가 0인지 확인하세요.
3. df2에서 문자로 되어있는 칼럼들을 원핫 인코딩 수행하여 숫자로 변환 후 처음 5개 행을 출력하세요

In [71]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [72]:
# A-1.
df.columns
df1 = df[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck']]
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [76]:
# A-2.
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   survived  891 non-null    int64   
 1   pclass    891 non-null    int64   
 2   sex       891 non-null    object  
 3   age       714 non-null    float64 
 4   sibsp     891 non-null    int64   
 5   parch     891 non-null    int64   
 6   fare      891 non-null    float64 
 7   embarked  889 non-null    object  
 8   deck      203 non-null    category
dtypes: category(1), float64(2), int64(4), object(2)
memory usage: 57.0+ KB


In [74]:
# A-2.
df2 = df1.drop('deck',axis=1)
df2.age.fillna(df2.age.mean(),inplace=True)
df2.embarked.fillna(method='ffill',inplace=True)
df2.isnull().sum().sum()

0

In [77]:
# A3.

pd.get_dummies(df2).head()

survived  pclass   age  sibsp  parch     fare  sex_female  sex_male  \
0         0       3  22.0      1      0   7.2500           0         1   
1         1       1  38.0      1      0  71.2833           1         0   
2         1       3  26.0      0      0   7.9250           1         0   
3         1       1  35.0      1      0  53.1000           1         0   
4         0       3  35.0      0      0   8.0500           0         1   

   embarked_C  embarked_Q  embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1