In [11]:
# 파이썬 random 함수
import random
# print(random.random()) #0.0~ 1.0 사이 출력
# print(random.randint(1,10)) #정수 반환
# print(random.uniform(10,20)) #실수 반환 
# random.randrange(10) #0~9 정수 반환
# random.choice([1,2,3,4,5]) #리스트 중 랜덤하게 하나 반환

i = [1,2,3,4,5]
# random.sample(i,5) #samle(뽑을 리스트,뽑을 갯 수) 순서를 랜덤으로 중복이 안되게 사용 함 / 리스트 요소를 중복 안되게 추출해줌

#random.shuffle(i) # 리스트를 랜덤 순서대로 섞음
#i

[3, 2, 4, 5, 1]

In [ ]:
# Numpy의 np.random
# rand : 0 ~ 1 사이의 균일 분포
# randn : (가우시안)표준 정규 분포
# randint : 균일 분포의 정수 난수



In [14]:
# 0.0 ~ 1.0 사이의 균일 분포인 실수
import numpy as np
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [20]:

np.random.randint(5) # 0 ~ 4 까지의 정수형 난수 출력
np.random.randint(1,20)
np.random.randint(10,size=10) # 중복 될 수 있음
np.random.randint(10,20,size=10)
np.random.randint(10,20,size=(3,5)) # 배열을 만들 수 있음

array([[13, 17, 15, 15, 10],
       [11, 15, 19, 13, 10],
       [15, 10, 11, 12, 14]])

In [135]:
np.random.choice([1,2,3,4,5])
np.random.choice(5,4,replace=False) # 0~4까지의 숫자 중 4개를 랜덤으로 추출 replace = 중복여부



array([4, 1, 0, 2])

In [154]:
list = [1,2,3,4,5]
np.random.shuffle(list) # list를 무작위로 섞음
list

[2, 5, 1, 4, 3]

In [156]:
np.random.randn(6)
np.random.randn(3,2)

array([[-0.46780647, -0.12940171],
       [ 0.90005154, -0.51565282],
       [ 0.52039958,  1.14104995]])

In [178]:
np.random.uniform(1,2,3) # 1 ~ 2 사이의 실수 3개를 뽑아줌
np.random.uniform(0,1,(2,3)) # 0 ~ 1 사이의 실수를 2행 3열 형태로 출력

array([[0.02910001, 0.91953144, 0.542457  ],
       [0.99114165, 0.38310289, 0.80666933]])

In [179]:
# random_sample은 uniform 하수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

<function RandomState.random>

In [ ]:
# Q. 고객 구매데이터 생성(id, 성별, 연령, 지역, 상품, 가격, 구매시간) 하고 데이터 프레임으로 변환한 후 아래 사항을 수행하세요.
## 구매 데이터 생성
id : 1번 ~ 1000번 일련번호(관측치 1000개) 
gender : 0,1 정수 난수 생성 
age : 10 ~ 80사이 정수 난수를 생성하고 범주화하여 age_cat 파생 
region : 1 ~ 10 사이 정수 난수 생성 
product : 1개 제품 이상 
price_avg_19 : 1000 ~ 50000 사이 실수 난수 생성하고 범주화하여 price_avg_cat 파생 
price_avg_20 : 1000 ~ 50000 사이 실수 난수 생성하고 범주화하여 price_avg_cat 파생 
qty_19 : 1 ~ 100 사이 정수 난수 생성하여('19년 구매 수량) 
qty_20 : 1 ~ 100 사이 정수 난수 생성하여('20년 구매 수량) 
time_19 : 01 ~ 24 사이 정수 난수 생성하고 오전, 오후, 야간 으로 범주화하여  time_cat_19 파생('19년에 가장 자주 구매한 시간대) 
time_20 : 01 ~ 24 사이 정수 난수 생성하고 오전, 오후, 야간 으로 범주화하여 time_cat 파생  ('20년에 가장 자주 구매한 시간대)  
구매액은 price * qty로 산출('19년, '20년 각각 계산)하여 pur_19, pur_20 컬럼으로 생성 
종속변수(결과변수)는 (pur_20 - pur_19)으로 계산하여 구매액 증감을 0(감소), 1(증가)로  범주화하여 pur_gap 컬럼 생성 
np.nan으로 각 컬럼별로 10개씩 null값을 삽입하고 각 칼럼의 특성을 고려한 null 값 처리 
## 인사이트 도출
통계적 분석 및 시각화하여 탐색한 후 불필요한 컬럼은 삭제하고 필요시 추가 파생변수 생성한 후 분석용 데이터셋을 작성하고 인사이트 3개 이상 도출
인사이트 도출하지 못한 경우 데이터를 수정하여 다시 탐색한 후 인사이트 도출 및 기술
## 데이터 ㅔ수정시 참조
구매액 증감에 영향을 주는 주요 요인과 관련된 인사이트를 만들 수 있는 데이터로 변경하는 점에 중점을 둠
구매 감소한 고객의 특성으로 성별, 지역, 선호제픔, 선호 구매시간대, 평균 구매가 level(저가, 중가, 고가)별로 데이터 수정
연령, 성별로 상품유형, 구매단가, 구매시간대 등을 복합적으로 그룹화하여 데이터 특성 부여
연도별로 상기한 사항들의 변동과 구매 감소간의 상관성을 부여하는 데이터 수정
데이터 수정은 불린 인덱싱으로 특정 그룹을 선택한 후 고객 특성에 맞는 값으로 변경

In [427]:
import numpy as np
import pandas as pd
import math
from sklearn.preprocessing import LabelEncoder

def price19_wow(a):
    if a == 1:
        price = np.random.uniform(1500,1600)
    elif a == 2:
        price = np.random.uniform(2400,2500)
    elif a == 3:
        price = np.random.uniform(3700,3800)
    elif a == 4:
        price = np.random.uniform(5900,6000)
    elif a == 5:
        price = np.random.uniform(8900,9000)
    else:
        price = '에러발생 : 19'
    return price

def price20_wow(a):
    if a == 1:
        price = np.random.uniform(2000,2100)
    elif a == 2:
        price = np.random.uniform(3200,3200)
    elif a == 3:
        price = np.random.uniform(4600,4700)
    elif a == 4:
        price = np.random.uniform(7300,7400)
    elif a == 5:
        price = np.random.uniform(42000,43000)
    else:
        price = '에러발생 : 20'
    return price


def pur(a,b):
    pur = a * b
    return pur

def gap(a):
    if a < 0:
        z = 0
    elif a > 0:
        z = 1
    else:
        z = '에러발생 : gap'
    return z
    

id = np.arange(1,1001) # id 일련번호 1부터 순차적으로 1000번까지 생성
gender = np.random.randint(0,2,size=1000)
age = np.random.randint(10,81,size=1000)
region = np.random.randint(1,11,1000)
product = np.random.randint(1,6,1000)
qty_19 = np.random.randint(1,101,size=1000)
qty_20 = np.random.randint(1,101,size=1000)
time_19 = np.random.randint(1,25,size=1000)
time_20 = np.random.randint(1,25,size=1000)


df = pd.DataFrame({'id':id,'gender':gender,'age':age,'region':region,'product':product,'qty_19':qty_19,'qty_20':qty_20,'time_19':time_19,'time_20':time_20})
price19_df = df['product'].apply(price19_wow)
price20_df = df['product'].apply(price20_wow)

df['price19'] = price19_df # 19년도 물건 가격
qty_19_d = df['qty_19']

df['price20'] = price20_df # 20년도 물건 가격
qty_20_d = df['qty_20']

price_19 = df['price19']
pur_19_df = pur(price_19,qty_19_d)
df['pur_19'] = pur_19_df # 19년도 구매액

price_20 = df['price20']
pur_20_df = pur(price_20,qty_20_d)
df['pur_20'] = pur_20_df # 20년도 구매액

pur_gap = df['pur_20'] - df['pur_19']
df['pur_gap'] = pur_gap.apply(gap) # 구매액 증감


#무작위 컬럼별 null값 10개 
df.iloc[232:252:2,0] = np.nan
df.iloc[132:152:2,1] = np.nan
df.iloc[332:352:2,2] = np.nan
df.iloc[632:652:2,3] = np.nan
df.iloc[732:752:2,4] = np.nan
df.iloc[32:52:2,5] = np.nan
df.iloc[832:852:2,6] = np.nan
df.iloc[932:962:3,7] = np.nan
df.iloc[132:172:4,8] = np.nan
df.iloc[232:302:7,9] = np.nan
df.iloc[102:132:3,10] = np.nan
df.iloc[532:552:2,11] = np.nan
df.iloc[542:592:5,12] = np.nan
df.iloc[2:52:5,13] = np.nan
# 확인
#print(df.isnull().sum())
#df['id'] = df['id'].fillna(method='ffill')+1
df = df.fillna(0)
df =df.astype('int')
##########################################################################
# Null값 채우는 연습 이후 상관 없는 데이터 삭제
df.drop(['id','region'],axis=1)
##########################################################################

# 남아 있는 데이터를 기준으로 기존의 데이터에 최대한 가깝게 복원
# 이전에 있는 공식을 사용한다면 비어 있는 값은 자연스럽게 채워진다 :)

price19_df = df['product'].apply(price19_wow)
price20_df = df['product'].apply(price20_wow)

df['price19'] = price19_df # 19년도 물건 가격
qty_19_d = df['qty_19']

df['price20'] = price20_df # 20년도 물건 가격
qty_20_d = df['qty_20']

price_19 = df['price19']
pur_19_df = pur(price_19,qty_19_d)
df['pur_19'] = pur_19_df # 19년도 구매액

price_20 = df['price20']
pur_20_df = pur(price_20,qty_20_d)
df['pur_20'] = pur_20_df # 20년도 구매액


df.corr() #상관관계를 파악하면 
# gap은 qty19(19년 구매 수량). qty20(20년 구매 수량)의 상관 계수가 높은 걸 통해 구매 수량이 직접적으로 영향을 많이 끼치는 것을 알 수 있다.
def pro_tr(a):
    if a == 1:
        product = '삼각김밥'
    elif a == 2:
        product = '콜라'
    elif a == 3:
        product = '도시락'
    elif a == 4:
        product = '보조배터리'
    elif a == 5:
        product = '명절선물세트'
    else:
        product = '불량품'
    return product

print(df['product'].unique())

df['product'] = df['product'].apply(pro_tr)
df_pd = pd.get_dummies(df['product'])
df_pd.sum()








[3 2 5 1 4 0]


도시락       166
명절선물세트    212
보조배터리     219
불량품        10
삼각김밥      190
콜라        203
dtype: int64

In [ ]:
# 가격대 별 구매 패턴
# 거래 일 넣어보기 요일 별 인사이트
# 
