## Numpy는 "numerical python"의 약자로 대규모 다차원 배열과 행렬연산에 필요한 다양한 함수를 제공
- Numerical python을 의미하는 넘파이는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

## Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅(Broadcast)기능 / 따로 나눠주지 않아도 각각 셀에 계산을 해줌
- C/C++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [ ]:
import numpy as np
data = np.random.randn(2,3) # 정규분포에서 숫자를 뽑아줌(randn)
print(data,'\n')
print(data * 10, '\n')
print(data + data, '\n')

다차원 배열

<img src='numpy차원.jpg' STYLE = 'width:500px;'>

In [ ]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

In [ ]:
arr2 = np.arange(1,9).reshape(2,4)
arr2

In [ ]:
print(arr2.ndim) # ndim = 차원 표시
print(arr2.shape)

In [ ]:
#각 배열 변환#
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(array3.ndim)
print(array3.shape)

In [ ]:
print(np.zeros(10),'\n') # 0으로 구성된 10개의 원소들
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)),'\n')

In [ ]:
print(np.ones(10),'\n') # 1으로 구성된 10개의 원소들
print(np.ones((3,6)),'\n')
print(np.ones((2,3,2)),'\n')

In [ ]:
arr3 = np.arange(15)
# arr3 = np.arange(1,15)
arr3

In [ ]:
# reshape 함수 #행과 열 수를 맞춰야 됨
arr3.reshape(3,5)
arr3.reshape(5,-1) # -1을 입력하면 나머지 열 수를 알아서 정리해줌
arr3.reshape(-1,15) # -1을 입력하면 나머지 행 수를 알아서 정리해줌


In [ ]:
# 5행 3열, 7행 25열 다차원 배열을 생성하세요
nar = np.arange(175).reshape(7,25)
nar1 = np.arange(15).reshape(5,3)

print(nar)
print(nar1)

In [ ]:
# 1~30연속된 정수로 1차원,2차원,3차원 배열을 생성하세요.
wow = np.arange(1,31)
wow1 = np.zeros((1,31))
wow2 = np.ones((3,2,10))
print(wow,'\n') # 1d
print(wow1,'\n') # 2d
print(wow2,'\n') # 3d

In [ ]:
# 연속된 정수 1~20으로 1차원 배열을 생성 후 2차원, 3차원으로 변환하세요
wow = np.arange(1,21)
print(wow,'\n') # 1d
print(wow.reshape(2,-1),'\n') # 2d
print(wow.reshape(2,2,-1),'\n') # 3d

In [ ]:
# 연속된 정수 1 ~ 30으로 2차원 배열을 생성한 후 1차원, 3차원 배열로 변환하세요.
h = np.arange(1,31).reshape(3,-1)
print(h)
print(h.reshape(-1))
print(h.reshape(3,2,-1))


In [ ]:
# 연속된 정수 1 ~ 24로 3차원 배열을 생성한 후 1차원, 2차원 배열로 변환하세요.
la = np.arange(1,25).reshape(3,2,4)
print(la)
print(la.reshape(-1))
print(la.reshape(3,8))


In [ ]:
# 배열을 리스트로 변환.
arr9 = np.arange(30).reshape(5,3,2)
arr9.tolist()

In [ ]:
a = np.full((2,2),7) #np.full ((행렬),값으로 채움) 
a

In [ ]:
# 항등행렬, 단위행렬
ar = np.eye(3)
ar

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.zeros_like(a) # zeros_like(a) : a의 값들을 0로 만들어라
b

In [ ]:
# 0 ~ 10 사이를 균등하게 50개로 나눠준다
np.linspace(0,10)

# numpy.linspace(start, stop, num=50, endpoint=True,
#                retstep=False, dtype=None, axis=0)[source]

# numint, optional
# Number of samples to generate. Default is 50. Must be non-negative.

In [ ]:
np.linspace(0,1,5,retstep=True)

In [ ]:
import matplotlib.pyplot as plt
x = np.linspace(0,1)
y = np.linspace(0,50)
plt.plot(x,y,'o')

In [ ]:
x = np.linspace(0,20,20)
y = np.linspace(0.1,1,20)
plt.plot(x,y,'r') # r,^,*

In [ ]:
print(np.log10(1.25892541))
print(np.log10(10))
np.logspace(0.1,1,20)

In [ ]:
x = np.linspace(0,20,20)
y = np.logspace(0.1,1,20)
plt.plot(x,y,'o')

In [ ]:
ar1 = np.array([1,2,3,4,5])
print(ar1.dtype)
float_ar1 = ar1.astype(np.float64)
print(float_ar1.dtype)

In [ ]:
numeric_string = np.array(['1.25','-9.5','42'],dtype=np.string_)
numeric_string.astype(float)

In [ ]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서
#실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
nu_1 = np.array(list_e) # 실수와 정수가 섞여 있으면 실수로 인식(실수에 정수가 다 포함 되어 있기 때문)
nu_2 = np.array(list_e,dtype=np.int64)
print(nu_1.dtype)
print(nu_2.dtype)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

In [ ]:
arr1 = arr * arr # 같은 위치에 있는 셀 끼리 계산

In [ ]:
arr2 = arr - arr

In [ ]:
arr2 > arr1 # 같은 위치에 있는 셀 boolean 값으로 반환

In [ ]:
ar2 = np.arange(1,10).reshape(3,3)
ar2

In [ ]:
ar2[2]

In [ ]:
#ar2[0][2]
ar2[0,2]

In [ ]:
ar2 = np.arange(20).reshape(5,4)
ar2

In [ ]:
ar2[:2,1:]

In [ ]:
# 과제
ar2 = np.arange(1,10).reshape(3,3)
ar2

In [ ]:
# 과제
# ar2 에서 슬라이싱을 사용해서 아래와 같이 출력하세요.
# #1
# [[1,2],
# [4,5]]
# #2
# (2가지 방법)
# [[4,5,6],
# [7,8,9]]
# #3
# [[1,2,3],
# [4,5,6],
# [7,8,9]]
# #4
# [[2,3],
# [5,6]]
# #5
# [1,4]

In [ ]:
# 1
ar2[:2,:2]

In [ ]:
# 2
print(ar2[1:3])
print(ar2[1:][:])

In [ ]:
# 3
ar2[::]

In [ ]:
# 4
ar2[:2,1:]

In [ ]:
# 5
ar2[:2,0]

In [ ]:
# Boolean Indexing
ar1 = np.arange(1,10)
print(ar1)
ar2 = ar1[ar1 > 5]
print(ar2)
print(ar1 > 5)

In [ ]:
indexes = np.array([5,6,7,8])
ar3 = ar1[indexes]
ar3

In [ ]:
# 1 ~ 14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는
# 불린 인덱스로 출력하세요

array_e = np.arange(1,15)
print((array_e / 2) > 5)
array_e[(array_e / 2) > 5]

In [ ]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data,'\n')

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob',2:]

In [ ]:
data[names != 'Bob']

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

In [ ]:
# 배열 전치와 축 바꾸기
ar = np.arange(15).reshape(3,5)
ar

In [ ]:
ar_1 = ar.T
ar = ar_1.transpose()

In [ ]:
np.random.seed(0)
tr = np.random.randn(6,3)
tr

In [ ]:
# 1 ~ 100 까지 배열에서 3의 배수인 것 만을 출력
tt = np.arange(1,101)
tt[tt%3==0]

In [ ]:
# 1 ~ 100 까지 배열에서 3, 5의 배수인 것 만을 출력
tt = np.arange(1,101)
tt[(tt%3==0) | (tt%5==0)]
#tt[(tt%3|tt%5)==0] 공배수

In [ ]:
ar = np.random.randn(5,4)
ar

In [ ]:
# 반올림
ar.mean().round(4)

In [ ]:
ar.sum().round(4)

In [ ]:
# 누적 합계
ar = np.arange(1,9)
print(ar)
ar.cumsum()

In [ ]:
ar = np.arange(9).reshape(3,3)
print(ar,'\n')
print(ar.cumsum(),'\n') # 1차원
print(ar.cumsum(axis=0),'\n') #2차원
print(ar.cumsum(axis=1))


In [ ]:
ar = np.random.randn(10)
print(ar,'\n')
#(ar > 0).sum()
len(ar[ar>0])

In [ ]:
# any 메서드 : 하나 이상의 값이 True 인지 검사
bools = np.array([False,False,True,True])
bools.any()

In [ ]:
bools.all()

In [ ]:
# 삼항식의 벡터화 버전 (조건,a,b) - 조건 참 = a, 거짓 = b
ar = np.random.randn(4,4)
print(ar)
np.where(ar > 0, 2, -2) # ar > 0 True = 2 반환 False = -2 반환

In [ ]:
# ar 에서 양수를 전부 2로 출력하세요
np.where(ar > 0 ,2,ar)


In [ ]:
# np.sort() : 원본에 반영이 안됨
ar = np.random.randn(5)
print(ar,'\n')
print(np.sort(ar),'\n')
print(ar)

In [ ]:
# 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
ar2 = np.array([[8,12],[7,1]])

sort_sr2_a0 = np.sort(ar2,axis=0)
print(sort_sr2_a0,'\n')
sort_sr2_a1 = np.sort(ar2,axis=1)
print(sort_sr2_a1)

In [ ]:
# ndarray.sort() : 원본 반영 됨
ar = np.random.randn(6)
print(ar,'\n')
ar.sort() # 값을 반환 안해서 출력해도 None 값 나옴
print(ar)


In [ ]:
li = list( range(120,0,-1) )
ar = np.array(li).reshape(2,3,4,5)
#ar = np.random.randn(2,3,2,3)
print(ar)
print('\n=============\n')
print(np.sort(ar,axis=0))
print('\n=============\n')

print('\n=============\n')
print(np.sort(ar,axis=1))
print('\n=============\n')

print('\n=============\n')
print(np.sort(ar,axis=2))
print('\n=============\n')

print('\n=============\n')
print(np.sort(ar,axis=3))
print('\n=============\n')

print('\n=============\n')
print(np.sort(ar,axis=4))
print('\n=============\n')

In [ ]:
# 열 방향 # 데이터프레임과 배열에서는 반대로 이루어져 있음
np.random.seed(0)
ar2 = np.random.randn(5,3)
print(ar2,'\n')
ar2.sort(1)
print(ar2,'\n')
ar2.sort(0)
print(ar2)

In [ ]:
# 행 방향
print(ar2,'\n')
ar2.sort(0)
print(ar2)
# 아직 검증이 덜 끝났는데 
# ar = np.random.randn(axis=0번째 자리 ,axis=1번째 자리 ,axis=2번째 자리 ,axis=3번째 자리 ) 인것 같아요

In [ ]:
ar = np.array([3,3,2,2,1,1])
np.unique(ar)

In [ ]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6]) #원소들의 위치를 True로 출력

In [ ]:
# 배열 데이터 입출력 : np.save, np.load(파일명.npy) 형식
arr = np.arange(10)
np.save('some_array',arr)

np.load('some_array.npy')


선형대수

<img src = '내적.jpg' STYLE = 'width:500px;'>

벡터 a를 벡터 b와 같은 방향의 성분과 그렇지 않은 성분으로 분해한다고 할 때 $|a|cosθ$의 길이는 벡터 b와 같은 방향의 성분 길이와 같다.  

벡터 a와 b의 내적은 벡터 b의 길이와 벡터 a에서 벡터 b와 같은 방향의 성분 길이를 곱한 것이다.

- 행렬 내적은 행렬 곱이며 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능
- 행렬 내적의 특성으로 왼쪽 행렬의 열개수와 오른쪽 행렬의 행개수가 동일해야 내적 연산 가능

In [ ]:
# 행렬곱 : x.dot(y), np.dot(x,y)
x = np.arange(1,7).reshape(2,3)
y = np.array([[6,23],[-1,7,],[8,9]])
print(x,'\n')
print(y,'\n')
# 결과는 2행 2열로 나옴
np.dot(x,y)

행렬 곱을 응용하여 신경망에 적용

<img src = '행렬곱.jpg' STYLE = 'width:500px;'>

In [267]:
# 역행렬 : 어떤 행렬 A와 곱했을 때 곱셈에 대한 항등원인 단위행렬 E가
# 나오는 행렬을 행렬 A의 역행렬이라고 함 np.linalg.inv()
np.random.seed(0)
mt1 = np.random.randint(1,4,size=(3,3))
print(mt1)
mt2 = np.linalg.inv(mt1)
np.dot(mt1,mt2) # 행렬 곱을 해서 
역행렬인지 확인

[[1 2 1]
 [2 2 3]
 [1 3 1]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [268]:
# a1, b1의 행렬 내적
a1 = np.arange(1,7).reshape(2,3)
b1 = np.arange(10,16).reshape(3,2)
np.dot(a1,b1)

array([[ 76,  82],
       [184, 199]])